name: tests

on:
    push:
      branches:
        - main
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    phpstan:
        runs-on: ubuntu-20.04
        name: phpstan-tests
        steps:
            -   uses: actions/checkout@v2
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress
            -   name: Run types tests with PHPStan
                run: composer phpstan

    tests:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php: ['8.0', '8.1']
                stability: [prefer-lowest, prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, mbstring
                  tools: composer:v2
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

            - name: Run tests
              run: composer run test-ci
